STATION_TOPIC_PREFIX = 'org.chicago.cta.station.arrivals'
TURNSTILE_TOPIC = 'turnstile'
STATION_FAUST_TABLE_TOPIC = 'org.chicago.cta.stations.table.v1'
WEATHER_TOPIC = 'org.chicago.cta.weather.v1'
TURNSTILE_SUMMARY_TOPIC = 'TURNSTILE_SUMMARY'
